//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by blogolee.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BLOGOLEE_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_ENDPOINT_DIALOG             129
#define IDD_BLOGID_DIALOG               130
#define IDD_DIALOG_HOTEL_INFO           131
#define IDD_DIALOG_PROXY_INFO           132
#define IDD_EDIT_AMAZON_ACCESS_KEY      133
#define IDD_BLOG_DIALOG                 136
#define IDD_ADD_BLOGINFO_DIALOG         137
#define IDD_PROCEEDING_DIALOG           138
#define IDD_BLOGOLEE_MINI_DIALOG        139
#define IDC_HAND2                       140
#define IDC_EDIT_ARTICLE_TITLE          1000
#define IDC_EDIT_ARTICLE                1001
#define IDC_EDIT_ARTICLE_EXTENDED       1002
#define IDC_EDIT_BLOG_PASSWORD          1003
#define IDC_EDIT_ARTICLE_KEYWORD        1004
#define IDC_EDIT_BLOG_USERNAME          1005
#define IDC_EDIT_BLOG_NAME              1006
#define IDC_RADIO_KEYWORD_ON            1007
#define IDC_RADIO_KEYWORD_OFF           1008
#define IDC_EDIT_ARTICLE_SUMMARY        1010
#define IDC_EDIT_TOPPAGE_URL            1012
#define IDC_EDIT_ENDPOINT_URL           1013
#define IDC_LIST_BLOGID                 1013
#define IDC_EDIT_BLOG_ID                1015
#define IDC_COMBO_FOODCD                1016
#define IDC_RADIO_SIMILARITY_ON         1017
#define IDC_RADIO_SIMILARITY_OFF        1018
#define IDC_EDIT_ASSOCIATE_ID           1019
#define IDC_EDIT_FOOD_KEYWORD           1020
#define IDC_BUTTON_FOOD_SEARCH          1021
#define IDC_LIST_CATEGORY               1022
#define IDC_WEB_HOTPEPPER               1023
#define IDC_BUTTON_GET_CATEGORIES       1024
#define IDC_BUTTON_SWITCH_BLOG          1025
#define IDC_BUTTON_BROWSE_BLOG          1026
#define IDC_COMBO_AREA_LIST             1027
#define IDC_STATIC_PROCEED_STRING       1027
#define IDC_COMBO_HOTEL_TYPE            1028
#define IDC_BUTTON_HOTEL_SEARCH         1029
#define IDC_WEB_JALAN                   1030
#define IDC_EDIT_SECOND                 1031
#define IDC_COMBO_AREA_LIST2            1031
#define IDC_EDIT_RAKUTEN_ID             1032
#define IDC_COMBO_BLOGKIND              1033
#define IDC_LIST_BLOG                   1034
#define IDC_BUTTON_ADD_BLOG             1035
#define IDC_EDIT_JALAN_SID              1035
#define IDC_COMBO_BLOG_LIST             1036
#define IDC_BUTTON_DELETE_BLOG          1036
#define IDC_EDIT_JALAN_PID              1036
#define IDC_EDIT_BLOGNAME               1037
#define IDC_BUTTON_MODIFY_BLOG          1037
#define IDC_BUTTON_JALAN_LINK           1037
#define IDC_EDIT_BLOGUSERNAME           1038
#define IDC_BUTTON_BACKWARD             1038
#define IDC_BUTTON_PROXY                1038
#define IDC_EDIT_BLOGPASSWORD           1039
#define IDC_BUTTON_FORWARD              1039
#define IDC_STATIC_HOTEL1               1040
#define IDC_EDIT_BLOGID                 1041
#define IDC_EDIT_HOTEL_NAME             1041
#define IDC_EDIT_ENDPOINTURL            1042
#define IDC_EDIT_CATCH_COPY             1042
#define IDC_BUTTON_MOREINFO             1043
#define IDC_EDIT_HOTEL_URL              1043
#define IDC_EDIT_BLOG_URL               1044
#define IDC_EDIT_DESCRIPTION            1044
#define IDC_EDIT_BLOGURL                1045
#define IDC_EDIT_HOTEL_ADDERESS         1045
#define IDC_EDIT_CHEKIN_TIME            1046
#define IDC_EDIT_CHECKOUT_TIME          1047
#define IDC_EDIT_IMAGE_URL              1048
#define IDC_EDIT_IMAGE_DESCRIPTION      1049
#define IDC_EDIT_TEXT_LINK              1050
#define IDC_EDIT1_IMAGE_LINK            1051
#define IDC_EDIT_SID                    1052
#define IDC_EDIT_PID                    1053
#define IDC_AFFILIATE_URL               1054
#define IDC_EDIT_PROXY_SERVER_NAME      1055
#define IDC_EDIT_PROXY_PORT_NUMBER      1056
#define IDC_EDIT_PROXY_USER_NAME        1057
#define IDC_BUTTON_LARGE                1057
#define IDC_EDIT_PROXY_PASSWORD         1058
#define IDC_BUTTON_SMALL                1058
#define IDC_STATIC_RECOMENDED           1059
#define IDC_VERSION                     1060
#define IDC_EDIT_AMAZON_ACCESS_KEY      1061
#define IDC_EDIT_ACCESS_KEY_ID          1062
#define IDC_WEB_URL                     1063
#define IDC_EDIT_ACCESS_KEY_SECRET      1063
#define IDC_MAIL_ADDR                   1064
#define IDS_MAIL_ADDR                   61204
#define IDS_WEB_URL                     61205
#define IDS_WEB_HOTPEPPER               61206
#define IDS_WEB_JALAN                   61207
#define IDS_TXT_CONTINUE_PROCEEDING     61208
#define IDS_VERSION                     61209
#define IDS_AMAZON_P001                 61210
#define IDS_AMAZON_P002                 61211
#define IDS_RAKUTEN_D001                61212
#define IDS_RAKUTEN_D002                61213
#define IDS_RAKUTEN_D003                61214

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
